import { createClient } from '../client';
import type {
  Delivery,
  DeliveryInsert,
  DeliveryUpdate,
  DeliveryStatusHistory,
  DeliveryStatusHistoryInsert,
  Driver,
  DriverInsert,
  DriverUpdate,
} from '../types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const supabase = createClient() as any;

// ============================================================================
// Drivers
// ============================================================================

export async function getDrivers(userId: string): Promise<Driver[]> {
  const { data, error } = await supabase
    .from('drivers')
    .select('*')
    .eq('user_id', userId)
    .eq('is_active', true)
    .order('name');

  if (error) throw error;
  return data || [];
}

export async function getAvailableDrivers(userId: string): Promise<Driver[]> {
  const { data, error } = await supabase
    .from('drivers')
    .select('*')
    .eq('user_id', userId)
    .eq('is_active', true)
    .eq('is_available', true)
    .order('name');

  if (error) throw error;
  return data || [];
}

export async function createDriver(driver: DriverInsert): Promise<Driver> {
  const { data, error } = await supabase
    .from('drivers')
    .insert(driver)
    .select()
    .single();

  if (error) throw error;
  return data;
}

export async function updateDriver(id: string, updates: DriverUpdate): Promise<Driver> {
  const { data, error } = await supabase
    .from('drivers')
    .update(updates)
    .eq('id', id)
    .select()
    .single();

  if (error) throw error;
  return data;
}

export async function deleteDriver(id: string): Promise<void> {
  const { error } = await supabase
    .from('drivers')
    .update({ is_active: false })
    .eq('id', id);

  if (error) throw error;
}

export async function updateDriverAvailability(id: string, isAvailable: boolean): Promise<Driver> {
  return updateDriver(id, { is_available: isAvailable });
}

export async function updateDriverLocation(
  id: string,
  location: { lat: number; lng: number }
): Promise<Driver> {
  return updateDriver(id, { current_location: location });
}

// ============================================================================
// Deliveries
// ============================================================================

export async function getDeliveries(
  userId: string,
  options?: {
    status?: Delivery['status'] | Delivery['status'][];
    driverId?: string;
    startDate?: string;
    endDate?: string;
    limit?: number;
  }
): Promise<Delivery[]> {
  let query = supabase
    .from('deliveries')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (options?.status) {
    if (Array.isArray(options.status)) {
      query = query.in('status', options.status);
    } else {
      query = query.eq('status', options.status);
    }
  }

  if (options?.driverId) {
    query = query.eq('driver_id', options.driverId);
  }

  if (options?.startDate) {
    query = query.gte('created_at', options.startDate);
  }

  if (options?.endDate) {
    query = query.lte('created_at', options.endDate);
  }

  if (options?.limit) {
    query = query.limit(options.limit);
  }

  const { data, error } = await query;

  if (error) throw error;
  return data || [];
}

export async function getDeliveryById(id: string): Promise<Delivery | null> {
  const { data, error } = await supabase
    .from('deliveries')
    .select('*')
    .eq('id', id)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }

  return data;
}

export async function getDeliveryByTrackingNumber(trackingNumber: string): Promise<Delivery | null> {
  const { data, error } = await supabase
    .from('deliveries')
    .select('*')
    .eq('tracking_number', trackingNumber)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }

  return data;
}

export async function createDelivery(delivery: Omit<DeliveryInsert, 'tracking_number'>): Promise<Delivery> {
  // tracking_number is auto-generated by trigger
  const { data, error } = await supabase
    .from('deliveries')
    .insert(delivery)
    .select()
    .single();

  if (error) throw error;

  // Add initial status to history
  await addDeliveryStatusHistory(data.id, 'pending', null, 'Delivery created');

  return data;
}

export async function updateDelivery(id: string, updates: DeliveryUpdate): Promise<Delivery> {
  const { data, error } = await supabase
    .from('deliveries')
    .update(updates)
    .eq('id', id)
    .select()
    .single();

  if (error) throw error;
  return data;
}

export async function updateDeliveryStatus(
  id: string,
  status: Delivery['status'],
  location?: { lat: number; lng: number },
  notes?: string
): Promise<Delivery> {
  const updates: DeliveryUpdate = { status };

  // Set timestamps based on status
  if (status === 'picked_up') {
    updates.picked_up_at = new Date().toISOString();
  } else if (status === 'delivered') {
    updates.delivered_at = new Date().toISOString();
  }

  const delivery = await updateDelivery(id, updates);

  // Add to status history
  await addDeliveryStatusHistory(id, status, location, notes);

  return delivery;
}

export async function assignDriver(deliveryId: string, driverId: string): Promise<Delivery> {
  const delivery = await updateDelivery(deliveryId, {
    driver_id: driverId,
    status: 'assigned',
  });

  await addDeliveryStatusHistory(deliveryId, 'assigned', null, 'Driver assigned');

  return delivery;
}

export async function markDeliveryAsDelivered(
  id: string,
  proofPhotoUrl?: string,
  signatureUrl?: string,
  notes?: string
): Promise<Delivery> {
  return updateDelivery(id, {
    status: 'delivered',
    delivered_at: new Date().toISOString(),
    delivery_photo_url: proofPhotoUrl,
    signature_url: signatureUrl,
    delivery_notes: notes,
  });
}

export async function rateDelivery(
  id: string,
  rating: number,
  feedback?: string
): Promise<Delivery> {
  return updateDelivery(id, {
    customer_rating: rating,
    customer_feedback: feedback,
  });
}

// ============================================================================
// Delivery Status History
// ============================================================================

export async function getDeliveryStatusHistory(deliveryId: string): Promise<DeliveryStatusHistory[]> {
  const { data, error } = await supabase
    .from('delivery_status_history')
    .select('*')
    .eq('delivery_id', deliveryId)
    .order('created_at', { ascending: true });

  if (error) throw error;
  return data || [];
}

export async function addDeliveryStatusHistory(
  deliveryId: string,
  status: string,
  location?: { lat: number; lng: number } | null,
  notes?: string
): Promise<DeliveryStatusHistory> {
  const record: DeliveryStatusHistoryInsert = {
    delivery_id: deliveryId,
    status,
    location: location || null,
    notes: notes || null,
  };

  const { data, error } = await supabase
    .from('delivery_status_history')
    .insert(record)
    .select()
    .single();

  if (error) throw error;
  return data;
}

// ============================================================================
// Stats
// ============================================================================

export async function getActiveDeliveries(userId: string): Promise<Delivery[]> {
  return getDeliveries(userId, {
    status: ['pending', 'assigned', 'picked_up', 'in_transit'],
  });
}

export async function getDeliveryStats(userId: string): Promise<{
  todayDeliveries: number;
  activeDeliveries: number;
  completedToday: number;
  avgDeliveryTime: number | null;
}> {
  const today = new Date();
  const startOfDay = new Date(today.setHours(0, 0, 0, 0)).toISOString();

  const [todayResult, activeResult] = await Promise.all([
    supabase
      .from('deliveries')
      .select('status, picked_up_at, delivered_at')
      .eq('user_id', userId)
      .gte('created_at', startOfDay),
    supabase
      .from('deliveries')
      .select('id', { count: 'exact', head: true })
      .eq('user_id', userId)
      .in('status', ['pending', 'assigned', 'picked_up', 'in_transit']),
  ]);

  if (todayResult.error) throw todayResult.error;

  type DeliverySummary = { status?: string; picked_up_at?: string | null; delivered_at?: string | null };
  const deliveries = (todayResult.data || []) as DeliverySummary[];
  const completedToday = deliveries.filter((d) => d.status === 'delivered').length;

  // Calculate average delivery time for completed deliveries
  let avgDeliveryTime: number | null = null;
  const completedWithTimes = deliveries.filter(
    (d) => d.status === 'delivered' && d.picked_up_at && d.delivered_at
  );

  if (completedWithTimes.length > 0) {
    const totalMinutes = completedWithTimes.reduce((sum: number, d) => {
      const pickupTime = new Date(d.picked_up_at!).getTime();
      const deliveryTime = new Date(d.delivered_at!).getTime();
      return sum + (deliveryTime - pickupTime) / (1000 * 60);
    }, 0);
    avgDeliveryTime = Math.round(totalMinutes / completedWithTimes.length);
  }

  return {
    todayDeliveries: deliveries.length,
    activeDeliveries: activeResult.count || 0,
    completedToday,
    avgDeliveryTime,
  };
}
